export const FETCH_FIVE_DAYS_WEATHER = 'FETCH_FIVE_DAYS_WEATHER';
export const FETCH_LOCATION = 'FETCH_LOCATION';
export const FETCH_TODAY_WEATHER = 'FETCH_TODAY_WEATHER';
export const FETCH_ADDITIONAL_TODAY_WEATHER = 'FETCH_ADDITIONAL_TODAY_WEATHER';
